server:
  port: 9081

spring:
  application:
    name: demo-seata-client-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/demo_seata_client_consumer?userUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: demo_tx_group

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false


## log
logging:
  level:
    # seata log
    "org.springframework.cloud.alibaba.seata.web": debug
    "io.seata": debug


## actuator
# http://localhost:8081/actuator/health
management:
  security:
    enabled: false # 关闭安全检查 （仅供测试）
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口
  endpoint:
    health:
      show-details: always