server:
  port: 9081

spring:
  application:
    name: demo-eureka-client-consumer


## actuator
# http://localhost:8081/actuator/health
management:
  security:
    enabled: false # 关闭安全检查 （仅供测试）
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口
  endpoint:
    health:
      show-details: always


## ribbon 配置，注意某些配置的首字母大写
#ribbon:
#  eager-load:  # 关闭懒加载，启用饥饿加载
#    enabled: true
#    clients: demo-eureka-client-producer
#  ConnectTimeout: 2000 # 连接超时时间
#  ReadTimeout: 4000 # 响应超时时间

# ribbon 特定服务配置
#demo-eureka-client-producer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡策略
# 超时重试，
# 最大超时时间 MAX(Response Time) = (ConnectTimeout + ReadTimeout) * (MaxAutoRetries + 1) * (MaxAutoRetriesNextServer + 1)
#    OkToRetryOnAllOperations: true # 所有Http方法都可以重试 （这里是为了测试，一般只允许GET或严格幂等都接口）
#    ConnectTimeout: 1000 # 连接超时时间
#    ReadTimeout: 2000 # 响应超时时间
#    MaxAutoRetries: 2 # 每台节点重试次数
#    MaxAutoRetriesNextServer: 2 # 可重试节点数