server:
  port: 10000

spring:
  application:
    name: demo-eureka


eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true # 默认以ip地址注册
  client:
    register-with-eureka: false # 关闭注册
    fetch-registry: false # 关闭拉取配置文件
#    service-url:
#      defaultZone: http://localhost:10001/eureka # 如果希望配置集群，只要相互引用即可
  server:
#    enable-self-preservation: false # 强制关闭服务自保 - 测试
    eviction-interval-timer-in-ms: 10000 # 服务剔除间隔时间

