server:
  port: 8081

spring:
  application:
    name: demo-eureka-client-producer


## actuator
# http://localhost:8081/actuator/health
management:
  security:
    enabled: false # 关闭安全检查 （仅供测试）
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口
  endpoint:
    health:
      show-details: always