scrape_configs:
  # 任意写，建议英文，不要包含特殊字符
  - job_name: 'spring'
    # 多久采集一次数据
    scrape_interval: 15s
    # 采集时的超时时间
    scrape_timeout: 10s
    # 采集的路径是啥
    metrics_path: '/actuator/prometheus'
    # 采集服务的地址，设置成上面Spring Boot应用所在服务器的具体地址。
    static_configs:
      - targets: ['host.docker.internal:8081']
  # node_exporter
  - job_name: node
    static_configs:
      - targets: ['ecs:9100']
  # mysqld_exporter
  - job_name: mysql
    static_configs:
      - targets: ['host.docker.internal:9104']
  # keycloak_exporter
#  - job_name: keycloak
#    # 多久采集一次数据
#    scrape_interval: 15s
#    # 采集时的超时时间
#    scrape_timeout: 10s
#    # 采集的路径是啥
#    metrics_path: '/auth/realms/master/metrics'
#    static_configs:
#      - targets: [ 'host.docker.internal:18080']
  # pushgateway
  - job_name: pushgateway
    # 保持原 instance，job 标签
    honor_labels: true
    static_configs:
      - targets: [ 'host.docker.internal:9091']
        labels:
          pushgateway: "true"
    # 增加新标签适配 dashboard
    metric_relabel_configs:
      - action: replace
        source_labels: [ "instance" ]
        regex: (.*)
        replacement: $1
        target_label: "kubernetes_pod_name"